name: 'publish'
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--target aarch64-apple-darwin'
          #   nosuargs: '--target aarch64-apple-darwin --features hide-su-link --config src-tauri/tauri.conf-nosu.json'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
            nosuargs: '--target x86_64-apple-darwin --features hide-su-link --config src-tauri/tauri.conf-nosu.json'
          - platform: 'ubuntu-20.04' # ubuntu-20.04, Tauri v1. Note that ubuntu-22.04 here can be used, but requires users to also be using 22.04
            args: ''
            nosuargs: '--features hide-su-link --config src-tauri/tauri.conf-nosu.json'
          - platform: 'windows-latest'
            args: ''
            nosuargs: '--features hide-su-link --config src-tauri/tauri.conf-nosu.json'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          ## maybe also libgtk-3-dev for ubuntu-20.04. Also if using ubuntu-22.04: libwebkit2gtk-4.1-dev libsoup2.4-dev

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Scoutfile Sender v__VERSION__'
          releaseBody: 'See the assets to download the version for your platform. This version shows the Science Untangled live app URL as well as the live data URL.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-nosu-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Scoutfile Sender v__VERSION__ (No Science Untangled link)'
          releaseBody: 'See the assets to download the version for your platform. This version shows only the live data URL, not the Science Untangled live app URL.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.nosuargs }}
